/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/home/paul/temu/install/share/qemu"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_OSS 1
#define CONFIG_VNC_TLS 1
#define QEMU_VERSION "0.9.1"
#define TEMU_HOME "/home/paul/temu"
#define PROJECT_HOME "/home/paul/temu/tracecap"
#define TAINT_ENABLED 1
#define DEFINE_BLOCK_BEGIN
#define DEFINE_INSN_BEGIN
#define DEFINE_INSN_END
#define DEFINE_EIP_TAINTED
#define TAINT_FLAGS 1
#define PRECISE_EFLAGS
#define PLUGIN_TRACECAP
#define CONFIG_SDL 1
#define CONFIG_UNAME_RELEASE ""
